In [1]:
import pandas as pd
import numpy as np

In [2]:
var = np.arange(20).reshape(5,4)

In [3]:
var

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
var.mean()

9.5

In [5]:
var[2:4,:3]
# 2:4 specifies the rows and :3 specifies the columns

array([[ 8,  9, 10],
       [12, 13, 14]])

In [6]:
var[2:4,:3].mean()

11.0

In [7]:
# numpy arrays are build on the idea of axes
var.mean(axis = 1)
#axis of 1 means the avg across each row

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [8]:
var.mean(axis =0)
# axis of 0 means the avg across each column

array([ 8.,  9., 10., 11.])

In [9]:
df = pd.read_csv(r'/Users/ooreladipo/general_assembly/oore/Unit2/data/restaurants.csv')

In [10]:
df.head()

id  visit_date  visitors calendar_date day_of_week  \
0  air_ba937bf13d40fb24  2016-01-13        25    2016-01-13   Wednesday   
1  air_ba937bf13d40fb24  2016-01-14        32    2016-01-14    Thursday   
2  air_ba937bf13d40fb24  2016-01-15        29    2016-01-15      Friday   
3  air_ba937bf13d40fb24  2016-01-16        22    2016-01-16    Saturday   
4  air_ba937bf13d40fb24  2016-01-18         6    2016-01-18      Monday   

   holiday       genre                          area   latitude   longitude  \
0        0  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
1        0  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
2        0  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
3        0  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   
4        0  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068  139.751599   

   reserve_visitors  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN

In [11]:
df['visitors'].mean()

20.973761245180636

In [12]:
df.mean()

visitors             20.973761
holiday               0.050673
latitude             35.613121
longitude           137.357865
reserve_visitors     16.699808
dtype: float64

In [13]:
df[['visit_date','visitors','id']]
# we're passing a list as an argument

visit_date  visitors                    id
0       2016-01-13        25  air_ba937bf13d40fb24
1       2016-01-14        32  air_ba937bf13d40fb24
2       2016-01-15        29  air_ba937bf13d40fb24
3       2016-01-16        22  air_ba937bf13d40fb24
4       2016-01-18         6  air_ba937bf13d40fb24
...            ...       ...                   ...
252103  2017-04-21        49  air_a17f0778617c76e2
252104  2017-04-22        60  air_a17f0778617c76e2
252105  2017-03-26        69  air_a17f0778617c76e2
252106  2017-03-20        31  air_a17f0778617c76e2
252107  2017-04-09        26  air_a17f0778617c76e2

[252108 rows x 3 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252108 entries, 0 to 252107
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   id                252108 non-null  object 
 1   visit_date        252108 non-null  object 
 2   visitors          252108 non-null  int64  
 3   calendar_date     252108 non-null  object 
 4   day_of_week       252108 non-null  object 
 5   holiday           252108 non-null  int64  
 6   genre             252108 non-null  object 
 7   area              252108 non-null  object 
 8   latitude          252108 non-null  float64
 9   longitude         252108 non-null  float64
 10  reserve_visitors  108394 non-null  float64
dtypes: float64(3), int64(2), object(6)
memory usage: 21.2+ MB


In [15]:
df.dtypes

id                   object
visit_date           object
visitors              int64
calendar_date        object
day_of_week          object
holiday               int64
genre                object
area                 object
latitude            float64
longitude           float64
reserve_visitors    float64
dtype: object

In [16]:
df[:50]

id  visit_date  visitors calendar_date day_of_week  \
0   air_ba937bf13d40fb24  2016-01-13        25    2016-01-13   Wednesday   
1   air_ba937bf13d40fb24  2016-01-14        32    2016-01-14    Thursday   
2   air_ba937bf13d40fb24  2016-01-15        29    2016-01-15      Friday   
3   air_ba937bf13d40fb24  2016-01-16        22    2016-01-16    Saturday   
4   air_ba937bf13d40fb24  2016-01-18         6    2016-01-18      Monday   
5   air_ba937bf13d40fb24  2016-01-19         9    2016-01-19     Tuesday   
6   air_ba937bf13d40fb24  2016-01-20        31    2016-01-20   Wednesday   
7   air_ba937bf13d40fb24  2016-01-21        21    2016-01-21    Thursday   
8   air_ba937bf13d40fb24  2016-01-22        18    2016-01-22      Friday   
9   air_ba937bf13d40fb24  2016-01-23        26    2016-01-23    Saturday   
10  air_ba937bf13d40fb24  2016-01-25        21    2016-01-25      Monday   
11  air_ba937bf13d40fb24  2016-01-26        11    2016-01-26     Tuesday   
12  air_ba937bf13d40fb24  2016-01-27        24    2016-01-27   Wednesday   
13  air_ba937bf13d40fb24  2016-01-28        21    2016-01-28    Thursday   
14  air_ba937bf13d40fb24  2016-01-29        26    2016-01-29      Friday   
15  air_ba937bf13d40fb24  2016-01-30         6    2016-01-30    Saturday   
16  air_ba937bf13d40fb24  2016-02-03        18    2016-02-03   Wednesday   
17  air_ba937bf13d40fb24  2016-02-04        12    2016-02-04    Thursday   
18  air_ba937bf13d40fb24  2016-02-05        45    2016-02-05      Friday   
19  air_ba937bf13d40fb24  2016-02-06        15    2016-02-06    Saturday   
20  air_ba937bf13d40fb24  2016-02-08        19    2016-02-08      Monday   
21  air_ba937bf13d40fb24  2016-02-09        15    2016-02-09     Tuesday   
22  air_ba937bf13d40fb24  2016-02-10        32    2016-02-10   Wednesday   
23  air_ba937bf13d40fb24  2016-02-11         3    2016-02-11    Thursday   
24  air_ba937bf13d40fb24  2016-02-12        26    2016-02-12      Friday   
25  air_ba937bf13d40fb24  2016-02-13         8    2016-02-13    Saturday   
26  air_ba937bf13d40fb24  2016-02-15        14    2016-02-15      Monday   
27  air_ba937bf13d40fb24  2016-02-16        15    2016-02-16     Tuesday   
28  air_ba937bf13d40fb24  2016-02-17        17    2016-02-17   Wednesday   
29  air_ba937bf13d40fb24  2016-02-18        22    2016-02-18    Thursday   
30  air_ba937bf13d40fb24  2016-02-19        43    2016-02-19      Friday   
31  air_ba937bf13d40fb24  2016-02-20        20    2016-02-20    Saturday   
32  air_ba937bf13d40fb24  2016-02-22         7    2016-02-22      Monday   
33  air_ba937bf13d40fb24  2016-02-23        16    2016-02-23     Tuesday   
34  air_ba937bf13d40fb24  2016-02-24        21    2016-02-24   Wednesday   
35  air_ba937bf13d40fb24  2016-02-25        21    2016-02-25    Thursday   
36  air_ba937bf13d40fb24  2016-02-26        32    2016-02-26      Friday   
37  air_ba937bf13d40fb24  2016-02-27        23    2016-02-27    Saturday   
38  air_ba937bf13d40fb24  2016-02-29        22    2016-02-29      Monday   
39  air_ba937bf13d40fb24  2016-03-01        19    2016-03-01     Tuesday   
40  air_ba937bf13d40fb24  2016-03-02        21    2016-03-02   Wednesday   
41  air_ba937bf13d40fb24  2016-03-03        20    2016-03-03    Thursday   
42  air_ba937bf13d40fb24  2016-03-04        37    2016-03-04      Friday   
43  air_ba937bf13d40fb24  2016-03-05        13    2016-03-05    Saturday   
44  air_ba937bf13d40fb24  2016-03-07        11    2016-03-07      Monday   
45  air_ba937bf13d40fb24  2016-03-08         8    2016-03-08     Tuesday   
46  air_ba937bf13d40fb24  2016-03-09        23    2016-03-09   Wednesday   
47  air_ba937bf13d40fb24  2016-03-10        31    2016-03-10    Thursday   
48  air_ba937bf13d40fb24  2016-03-11        37    2016-03-11      Friday   
49  air_ba937bf13d40fb24  2016-03-12        25    2016-03-12    Saturday   

    holiday       genre                          area   latitude   longitude  \
0         0  Dining bar  Tōkyō-to Minato-ku Shibakōen  35.658068 

In [17]:
df[:50].mean()

visitors             20.780000
holiday               0.020000
latitude             35.658068
longitude           139.751599
reserve_visitors      5.833333
dtype: float64

In [18]:
df[['visitors','holiday','reserve_visitors']][:200].mean()

visitors            25.400000
holiday              0.015000
reserve_visitors     5.263158
dtype: float64

In [ ]:
# iloc allows you to look up items by their INDEX
# iloc is index based location
df.iloc[:250,-4]