<a href="https://colab.research.google.com/github/ladipoore/DAT-1019/blob/master/imdb_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import pandas as pd
import numpy as np

In [66]:
pwd

'/content'

In [67]:
df = pd.read_csv('IMDB.csv')

In [68]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# New Section

In [69]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [70]:
df['review'].iloc[1]


'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [71]:
#shuffling the data
df=df.sample(frac=1)

In [72]:
df.head()

review sentiment
31408  After wasting 2 hours of my life watching this...  negative
3852   Wow, not only is this film a "new lesson in re...  negative
7405   Alexander Nevsky is a series of superb sequenc...  positive
39388  I don't understand why everyone hates this mov...  positive
41037  This movie is actually so poor in its desperat...  negative

In [73]:
X,y = df['review'],df['sentiment']
y.replace(['positive','negative'],[1,0], inplace=True)
X_train, X_test = X[:40000], X[40000:]
y_train, y_test = y[:40000], y[40000:]

In [74]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [75]:
#initialize the tokenizer and set the number of words as 10k
tokenizer = Tokenizer(num_words=10000)

In [76]:
tokenizer.fit_on_texts(X_train)

In [77]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'a': 3,
 'of': 4,
 'to': 5,
 'is': 6,
 'br': 7,
 'in': 8,
 'it': 9,
 'i': 10,
 'this': 11,
 'that': 12,
 'was': 13,
 'as': 14,
 'for': 15,
 'with': 16,
 'movie': 17,
 'but': 18,
 'film': 19,
 'on': 20,
 'not': 21,
 'you': 22,
 'are': 23,
 'his': 24,
 'have': 25,
 'be': 26,
 'one': 27,
 'he': 28,
 'all': 29,
 'at': 30,
 'by': 31,
 'an': 32,
 'they': 33,
 'so': 34,
 'who': 35,
 'from': 36,
 'like': 37,
 'or': 38,
 'just': 39,
 'her': 40,
 'about': 41,
 'if': 42,
 'out': 43,
 "it's": 44,
 'has': 45,
 'there': 46,
 'some': 47,
 'what': 48,
 'good': 49,
 'more': 50,
 'when': 51,
 'very': 52,
 'up': 53,
 'no': 54,
 'my': 55,
 'time': 56,
 'even': 57,
 'she': 58,
 'would': 59,
 'which': 60,
 'only': 61,
 'really': 62,
 'story': 63,
 'see': 64,
 'their': 65,
 'had': 66,
 'can': 67,
 'me': 68,
 'well': 69,
 'were': 70,
 'than': 71,
 'much': 72,
 'we': 73,
 'bad': 74,
 'get': 75,
 'been': 76,
 'do': 77,
 'other': 78,
 'great': 79,
 'will': 80,
 'also': 81,
 'people': 82,
 

In [78]:
X_train = tokenizer.texts_to_sequences(X_train)
X_test = tokenizer.texts_to_sequences(X_test)

In [79]:
X_train[1]

[1377,
 21,
 61,
 6,
 11,
 19,
 3,
 169,
 2102,
 8,
 145,
 74,
 1281,
 18,
 81,
 3,
 2102,
 8,
 145,
 74,
 19,
 236,
 89,
 75,
 68,
 359,
 10,
 2520,
 1,
 1104,
 4,
 1510,
 785,
 18,
 30,
 1,
 168,
 56,
 27,
 203,
 959,
 51,
 3,
 17,
 6,
 381,
 8,
 418,
 22,
 1058,
 43,
 20,
 1,
 770,
 1,
 111,
 4,
 6,
 41,
 3,
 1338,
 1523,
 2873,
 7176,
 12,
 34,
 553,
 5,
 2061,
 83,
 1,
 5294,
 3662,
 1,
 5,
 1666,
 5332,
 83,
 4408,
 261,
 1296,
 1,
 369,
 147,
 22,
 117,
 1296,
 23,
 29,
 121,
 1,
 543,
 1928,
 82,
 1105,
 137,
 3,
 2683,
 261,
 904,
 2,
 3,
 1338,
 1514,
 23,
 265,
 5,
 857,
 43,
 1,
 3635,
 195,
 236,
 132,
 82,
 1938,
 27,
 155,
 2904,
 1,
 384,
 1510,
 36,
 93,
 20,
 29,
 73,
 64,
 6,
 1296,
 263,
 3,
 1816,
 255,
 20,
 171,
 708,
 8,
 1699,
 161,
 18,
 1510,
 2,
 6877,
 2,
 4173,
 31,
 2110,
 4,
 3411,
 2,
 580,
 237,
 11,
 6,
 3,
 1038,
 19,
 1,
 19,
 66,
 5,
 26,
 2180,
 83,
 623,
 2,
 51,
 336,
 21,
 1050,
 30,
 1,
 6597,
 4,
 1,
 1296,
 1,
 550,
 7511,
 23,
 178,
 592,
 

In [80]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train = pad_sequences(X_train, maxlen =250)
X_test = pad_sequences(X_test, maxlen=250)

In [81]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,  100, 3018,
        230,  620,    4,   55,  114,  148,   11,   17,   20,  508,  315,
        690,   10,  412,  142,    2,   47,    4,    1,  859,  835,    5,
       3096,  538,    4,  135,   10,  288,    9,    8,    1,   86,  276,
          8,    1,   61,  147,   12,   10,   67,  101,    4,    6,   12,
          1,  523, 1308, 6543,    5,   68,   18,   11,   17,   13,    3,
        932,  448,    4,  773,    9, 1027,   20,  171,  657,    2,    5,
         64,   12,   44, 2130,   20,  859,   14,   

In [82]:
from tensorflow.keras import models
from tensorflow.keras import layers


In [83]:
mod = models.Sequential([#we store all 10000 words in our list and set the number of weights associated with each word as 64
                         layers.Embedding(10000,64,input_length = 250),
                         layers.Flatten(),
                         layers.Dense(32, activation='relu'),
                         layers.Dense(32, activation='relu'),
                         layers.Dense(1, activation='sigmoid')
                         ])


In [84]:
mod.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 250, 64)           640000    
_________________________________________________________________
flatten_4 (Flatten)          (None, 16000)             0         
_________________________________________________________________
dense_12 (Dense)             (None, 32)                512032    
_________________________________________________________________
dense_13 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 33        
Total params: 1,153,121
Trainable params: 1,153,121
Non-trainable params: 0
_________________________________________________________________


In [85]:
mod.get_weights()

[array([[ 3.5781477e-02,  4.0315092e-05, -3.8150847e-02, ...,
          4.5898668e-03,  2.1065485e-02, -3.8474597e-02],
        [ 2.9953349e-02,  1.2072694e-02, -4.0797926e-02, ...,
          1.7817728e-03, -1.0703456e-02, -1.6418360e-02],
        [-9.2430487e-03, -3.3452168e-02, -3.4902941e-02, ...,
         -1.3543677e-02, -1.4689099e-02, -1.8251061e-02],
        ...,
        [-3.0239332e-02, -1.3603795e-02, -1.3895273e-02, ...,
          2.6644673e-02, -4.0132903e-02, -7.5566769e-04],
        [ 3.8498465e-02,  4.1122530e-02, -1.7088316e-02, ...,
          4.0606234e-02,  2.0265792e-02,  4.8180189e-02],
        [-2.9530501e-02, -2.5206435e-02,  1.7691758e-02, ...,
         -4.1960478e-02,  1.3337996e-02, -4.1476429e-02]], dtype=float32),
 array([[ 1.4227673e-02,  8.7289158e-03, -9.9541023e-03, ...,
          4.4051912e-03, -1.2172945e-04, -5.0681336e-03],
        [ 9.2071518e-03, -4.3901373e-03,  1.8187400e-02, ...,
          1.2101095e-02,  1.3118699e-02, -7.2418312e-03],
        [-

In [86]:
mod.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])

In [87]:
mod.fit(X_train,y_train.values,validation_split=0.2, epochs=5)

Epoch 1/5
1000/1000 [==============================] - 10s 10ms/step - loss: 0.4718 - acc: 0.7383 - val_loss: 0.2661 - val_acc: 0.8899
Epoch 2/5
1000/1000 [==============================] - 10s 10ms/step - loss: 0.0952 - acc: 0.9680 - val_loss: 0.3810 - val_acc: 0.8665
Epoch 3/5
1000/1000 [==============================] - 10s 10ms/step - loss: 0.0162 - acc: 0.9951 - val_loss: 0.6135 - val_acc: 0.8668
Epoch 4/5
1000/1000 [==============================] - 10s 10ms/step - loss: 0.0120 - acc: 0.9960 - val_loss: 0.6467 - val_acc: 0.8612
Epoch 5/5
1000/1000 [==============================] - 10s 10ms/step - loss: 0.0099 - acc: 0.9961 - val_loss: 0.6791 - val_acc: 0.8661


In [88]:
mod.predict(X_test)

array([[9.4936615e-01],
       [2.5665031e-07],
       [4.2879516e-01],
       ...,
       [9.8362303e-01],
       [1.2683868e-04],
       [1.0000000e+00]], dtype=float32)

In [89]:
mod.evaluate(X_test, y_test.values)

313/313 [==============================] - 1s 2ms/step - loss: 0.6615 - acc: 0.8669


[0.661544144153595, 0.8669000267982483]